class ActivitySuggestion {
  final String title;
  final String description;
  final String iconName;
  final List<String>
  weatherConditions; // Weather conditions suitable for this activity
  final double?
  minTemperature; // Minimum temperature suitable for this activity
  final double?
  maxTemperature; // Maximum temperature suitable for this activity
  final bool isAiGenerated; // Whether this suggestion was generated by AI

  ActivitySuggestion({
    required this.title,
    required this.description,
    required this.iconName,
    required this.weatherConditions,
    this.minTemperature,
    this.maxTemperature,
    this.isAiGenerated = false, // Default to false for predefined activities
  });

  // Check if this activity is suitable for the given weather conditions
  bool isSuitableFor(String weatherCondition, double temperature) {
    bool isWeatherSuitable = weatherConditions.contains(weatherCondition);
    bool isTemperatureSuitable = true;

    if (minTemperature != null && temperature < minTemperature!) {
      isTemperatureSuitable = false;
    }

    if (maxTemperature != null && temperature > maxTemperature!) {
      isTemperatureSuitable = false;
    }

    return isWeatherSuitable && isTemperatureSuitable;
  }

  // Predefined list of activity suggestions
  static List<ActivitySuggestion> getPredefinedActivities() {
    return [
      ActivitySuggestion(
        title: '散步',
        description: '在阳光明媚的日子里，去公园或湖边散步，享受新鲜空气和阳光。',
        iconName: 'walk',
        weatherConditions: ['Clear', 'Clouds'],
        minTemperature: 15,
        maxTemperature: 30,
      ),
      ActivitySuggestion(
        title: '野餐',
        description: '带上美食和毯子，在公园或草地上享受一次野餐。',
        iconName: 'picnic',
        weatherConditions: ['Clear'],
        minTemperature: 20,
        maxTemperature: 30,
      ),
      ActivitySuggestion(
        title: '骑自行车',
        description: '骑自行车探索城市或乡村的美丽风景。',
        iconName: 'bike',
        weatherConditions: ['Clear', 'Clouds'],
        minTemperature: 15,
        maxTemperature: 28,
      ),
      ActivitySuggestion(
        title: '摄影',
        description: '带上相机，捕捉阳光下的美丽瞬间。',
        iconName: 'camera',
        weatherConditions: ['Clear', 'Clouds'],
        minTemperature: 10,
      ),
      ActivitySuggestion(
        title: '户外瑜伽',
        description: '在户外进行瑜伽练习，感受阳光和自然的能量。',
        iconName: 'yoga',
        weatherConditions: ['Clear'],
        minTemperature: 18,
        maxTemperature: 28,
      ),
    ];
  }
}
